### ISSUE TITLE
Remove completely our cookie banner

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/wishlist#1]
## What is the need / problem ?

Our cookie banner is not responsive on on some old version of Safari (we never managed to reproduce, but we receive from time to time support request saying they are unable to see the "accept button. The workaround is to flip the iPad horizontally (yes nobody thinks about it....).. And...everyone is annoyed by cookie banners. Thanks to Matomo, we can remove it.

There is a lot of confusion saying GPDR is about cookie banner, and our current implementation of the cookie banner is actually a bit based on this missconception.

  So: what does the law say? Here is a [translation of this page](https://www.cnil.fr/fr/cookies-solutions-pour-les-outils-de-mesure-daudience):

 *The management of a website or application almost always requires the use of statistics on traffic and/or performance.*
*Some audience measurement tracers (*this includes Matomo!*) may be **exempted from consent.***

*The condition for being able to use audience measurement tracers without consent is to ensure that they are **strictly necessary for the provision of an online communication service at the express request of the user**, in accordance with article 82 of the French Data Protection Act.*

*In order to limit itself to what is strictly necessary for the provision of the service, the CNIL stresses that these tracers must :*

*- have a purpose strictly limited to the sole measurement of the audience of the site or application (performance measurement, detection of navigation problems, optimisation of technical performance or ergonomics, estimation of the power of the necessary servers, analysis of the content consulted), for the exclusive account of the publisher ;*
*- not to allow the global monitoring of the navigation of the person using different applications or browsing on different websites;*
*- serve only to produce anonymous statistical data;*
*- not to lead to a cross-checking of the data with other processing operations or to the data being passed on to third parties.*

However the law requires:

*- users be informed of the implementation of these tracers, for example via the privacy policy of the site or the mobile application ;*
*- the lifetime of the trackers should be limited to a period that allows a relevant comparison of audiences over time, as is the case for a 13-month period, and that it should not be automatically extended for new visits;* **This bit is the only one Matomo is not doing by default, but we can manually change this 13-month period**
*- the information collected through these tracers should be kept for a maximum period of 25 months*; **all good Matomo is keeping them for 24 months**
*- the above-mentioned life and retention periods shall be periodically reviewed in order to limit them to the strict necessary.*

**To conclude**: all our cookies currently are strictly necessary! So by default they do not required consent. As for Matomo, we just need to check about the 13-month period aspect, but the rest of the criteria are already met (we don't store IP addresses entirely). Also I've changed this setting:

![image](https://user-images.githubusercontent.com/6525576/120997835-d3a12d80-c787-11eb-8821-7cf3a43e86bd.png)

It was before disabled, so it meant that all users asking their browser to not track them were still tracked. I hope everyone agrees that we do not wish to force anything like this to our users.

**Does this mean we don't need to be transparent about our cookies?**

I don't think so. Also our privacy policy or cookie page should still allow to remove Matomo's cookie. But **these settings could enable us to design a dedicated page for this**, instead of a mandatory/violent banner that forces you to accept stuff you don't understand.

So this proposal is about removing the mandatory banner, not removing our transparency around our :cookie: 

## Who does it impact ?

All first time users and all users using private browsing. Not to mention specifically for OFN our cookie banner is not responsive 

## What does this problem affect (and how many, if known)?

Users' onboarding to the platform.

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

The banner can already be disabled in super admin, so the only work remaining here would be to check for the 13month period cookie. Maybe this can be a papercut.

## Connected wishlist and discovery discussions* [list precedent discussions]

It removes also the need to think about "compliance" with existing cookie extensions: https://github.com/openfoodfoundation/openfoodnetwork/issues/5328

## Is Papercut or wishlist item/feature candidate?

_to be completed by the product team_

**Comment by andrewpbrett** [comment]
Notes from paper cut meeting: 

Anything to do with Matomo is probably not a paper cut :)

**Comment by Erioldoesdesign** [comment]
Eriol will add an issue separate to this one but connected -> will add an issue to [welcome new designers](https://github.com/openfoodfoundation/design/projects/1) in the welcome design board to 'investigate' cookie messaging generally.

**Comment by almet** [comment]
Hi, I'm willing to work on this if that's possible, but I'm not sure how this should be implemented.

Should I "just" remove the cookie banner from the mainstream app, or should we have a specific flag to disable it for specific instances?

**Comment by RachL** [comment]
hello @almet thanks for your interest in this! The flag already exist actually. But an instance within the EU using Matomo can only disable the banner if all the criteria are met. And currently this one isn't : 

_the lifetime of the trackers should be limited to a period that allows a relevant comparison of audiences over time, as is the case for a 13-month period, and that it should not be automatically extended for new visits;_

So the work involves diving into how the OFN software is handling and communicating with Matomo. If you are up for it, I can create an issue in the main repo and give you access to a testing account on Matomo side.

**Comment by almet** [comment]
Thanks for your quick answer.

First, after checking back from my Linux machine, I cannot seem to reproduce the error I had (which I think was related to a banner that was on the frontpage of CoopCircuits, and with Cookies, which led me here). I will check again on a windows machine when I get the chance. 

But, for this issue, it seems that it's mostly configuration on the Matomo side. I've never used this tool, but according to their [GPDR page](https://matomo.org/gdpr-analytics/) they make it possible to comply with GPDR by exposing a lot of options. That should be enough?

It seems you know more than me about what's required, so it might be quicker that you have a look, but if you prefer I can also have a quick look and see what I can find.

Thanks!

**Comment by almet** [comment]
There is another way to look at the "problem" here :-) One might want to not track the users at all, and thus wouldn't need to issue a GPDR warning.

I'm not sure how and if this is possible with Matomo, but there are alternatives out there, such as [Goatcounter](https://www.goatcounter.com/) that I discovered today by accident, so I thought I would let you know :-)

**Comment by RachL** [comment]
hello @almet thanks for sharing, it seems a great tool indeed! However I don't think we will change our tool in the short term. What's interesting with Matomo is that it is open source but also it is a tool that is approved by the CNIL in France. They even share documentation online on how to use it : https://www.cnil.fr/fr/cookies-solutions-pour-les-outils-de-mesure-daudience

This is reassuring for our users that we use a tool recognized by the authorities.

Regarding GDPR, actually what we are trying to do here is not to be compliant with GDPR, but more to remove the banner (consent) while staying compliant to GDPR.

Re-diving into this made me see that Matomo has issued a new exemption guide : https://www.cnil.fr/sites/default/files/atoms/files/matomo_analytics_-_exemption_-_guide_de_configuration.pdf

I don't see in this guide the mention of the 13 months cookie duration. This was not something I could change as super user, but more something a dev had to add in the tracking code as mentioned here : https://www.it-connect.fr/chapitres/matomo-et-la-conformite-cnil-rgpd/

So now I don't know anymore if we need to do this in order to remove the cookie banner...

The only thing we don't do according to this new guide is that (again as I can't change the tracking code by myself) I didn't add the line `paq.push(['HeatmapSessionRecording::disable']);`

but heatmaps are desactivated (at least for FR).

ping @filipefurtad0 it's important that you are aware of this changes. The english version of the guide is here: https://matomo.org/wp-content/uploads/2021/10/Matomo-Analytics-Exemption-from-Tracking-Consent-in-France-CNIL.pdf. Most of the changes were applied to FR only apart from the deactivation of the "live" visitor logs. Also, if the person has activated "do not track" in their browser we don't track them. It's important to remember that browsers like Firefox activate do not track by default. And we have a lot of Firefox users in FR :) It's not a big deal, just something to bear in mind when comparing analytics across countries.
