### ISSUE TITLE
Adjust Backoffice Order Flow: switch steps "Customer Details" <> "Add products"

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/wishlist#107]
**This is WIP**

## What is the need / problem?

Currently the BO flow is not intuitive, user have to go back and forth to complete an order
By some (hopefully) simple adjustments we could improve the usability a lot.
This is one of 3 “Papercuts”, which still need tech input 

We propose to adjust the Backoffice Order Flow by switching the steps of _Customer Details_ <> _Order Details_, which will improve the UX of the flow and align it more with the shopfront flow.

1. Choose Distributor & OC
2. Choose Customer (or enter customer details for guest user)
3. Order Details (Add products + select shipping method)
4. Select payment

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_

## Potential solutions that will solve the problem?

![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/4ee7f46e-0c89-457a-a845-935ef73dad5e)

## Connected wishlist and discovery discussions
openfoodfoundation/openfoodnetwork#8912

## Is Papercut or feature candidate?

Papercut

**Comment by jaycmb** [comment]
I d say 
- Papercut from product side
- No design input needed

**Comment by andrewpbrett** [comment]
This is likely papercut sized; the only potential issue would be if there are elements on the second screen that depend on the first, but I think it could be worked around in the 1/2 dev day.

**Comment by lin-d-hop** [comment]
Covered by:
https://github.com/openfoodfoundation/openfoodnetwork/issues/8912
