### ISSUE TITLE
Basic Voucher / Promo Code

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/wishlist#120]
## What is the need / problem?

We have many many requests for use of promo codes or vouchers. This can be for:
* Promotional purposes - 10% off your next order, $10 off your next order etc
* Food justice option - giving people a discount ongoing
We can use tagging to do this, and we do come up with ways to do that. But tagging requires knowing the customer in advance, and complex management of tags to remove tags etc. We need a way to give a discount to someone who is ordering for the first time

## Which type of users does this problem affect (and how many, if known)?
_e.g._
_- Shoppers_ - enticement to shop, get discount
_- Hub Managers (MCFEs)_ promotional codes
_- Producers_
_- Instance Managers_ - yes because we come up with complex workarounds
_- Other (Please specify)_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

**Use Fee Structure**
* Create a fee type 'promo' that has an additional field for 'code / name' 
* Enterprise can create one / many promo 'fees', set tax codes do whatever. Fees can be set to negative, we use this a lot, so promo 'fee' can be -$10, -$10% etc
* If order cycle has a promo code attached (perhaps only as coord fee) then Promo code box appears in checkout
* When Customer enters promo code, the fee adjustment is added to the order
NB. Would be better if we can restrict orders to one per customer, but minimal implementation might just be that Hub needs to turn it off. 

**Promo Code Table**
* Name: amount / calculation

## Connected wishlist and discovery discussions* [list precedent discussions]
This does not solve the account credit problem, but it does enable us to operationalise 'Pay It forward' and other food justice options, as well as promotional codes. Related discussions to that 
*https://community.openfoodnetwork.org/t/enable-customers-to-pay-partially-or-fully-with-their-credits/1211
https://github.com/openfoodfoundation/wishlist/issues/75

## Is Papercut or feature candidate?
I suspect we could break this into multiple papercuts if the general approach were agreed.

_Add papercut or feature label to answer the question. If you are not sure, don't worry product team will cover :-)_

**Comment by RachL** [comment]
closing this one as the voucher project is now going on
