### ISSUE TITLE
Including product tax category in the notification emails

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/wishlist#13]
how big a job would it be to include the tax category in the notification emails?  As we are producing Quickbooks invoices for Stroudco shoppers as soon as the order confirmation email goes out, it would help Oliver a lot to be able to see straight away which items are VAT-able and which aren't without getting a report up.

If it can't be done easily, we'll either try and tell from memory or we might mark all VAT items with "(v)" in the product description.

**Comment by andrewpbrett** [comment]
This depends a little bit on how we want things formatted in the html version of the email, (so maybe needs a little design input), but providing the information on the product tax category to the emails should be a fairly small task.

**Comment by RachL** [comment]
We are closing this because it has not enough specification to be handle right now and we don't know if it is still needed. We can reopen if this is still a needed and I'll be happy to help on creating a new issue.
