### ISSUE TITLE
Display "only X left" in shopfront when there are less than or Y units of stock left

### ISSUE THREAD

**Issue by adele-ofn** [openfoodfoundation/wishlist#146]
## What is the need / problem?
It would improve the shopper experience (and potentially incentivise purchasing) if customers could see how many items are left for a given product.

## Which type of users does this problem affect (and how many, if known)?
- Shoppers
- Producers
- Hubs

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Display the "on hand" amount, which appears in each shop's backoffice, in the shopfront.

## Is Papercut or feature candidate?
Feature

**Comment by RachL** [comment]
Papercut meeting notes : 

- As it is an important shopping experience choice, a toggle in the enterprise profile should activate or deactivate the choice of displaying this message

- this is only a confirmed papercut if the cart page is NOT considered as part of the scope

- the message should appear under the Add button in the shopfront. Color should be OFN red, font size should be small => we need to check available message size when writing properly the issue

**Comment by tschumilas** [comment]
Looking for clarity -  is the 'y' amount set OFN-wide,  or instance wide,    enterprise wide,   or OC wide?  (The only reason I mention OC is that we have a funded feature to allow payment methods and shipping methods to be set at the OC level -  and I'm wondering if this issue has a similar dynamic...?)  (I don't have a point of view on this -  just flagging the question...)

**Comment by RachL** [comment]
Yes for papercut purpose the Y will be set at OFN level :+1:

**Comment by RachL** [comment]
Draft issue : 

## Description
**- As a:** enterprise user
**- On page:** shopfront only => **cart page remains the same**
**- I want to be able to do:** Activate the ability for the shopper to see that 3 product variant are left or less.

The number 3 will be for now hardcoded: no possibility to change it. We can create a superadmin feature to change this number in a later papercut.

To activate the feature, an enterprise user needs to go to their shop preferences and see a new radio button called `SEE PRODUCT STOCK`

What's this? text : `Allows shoppers to see when there are only 3 product left in stock or less`.

Mockup: https://design.penpot.app/#/view/41afef30-7d1f-11ec-9ea7-96385a0e391f?page-id=e586bdc1-acd0-11eb-bb49-81aaa3a367f9&index=0&share-id=64c46680-7d3e-11ec-a93c-e5d362d27ee9

By default the radio button should be on "Disabled".

## Acceptance Criteria & Tests

*Scenario 1 : the feature is activated by shopfront manager*

1. Log in as enterprise with shopfront
2. Check the feature is disabled by default
3. Activate the feature
4. Check that all variant with on_hand value being 3 or less are showing this message to either a guest shopper or a loggedin one: 

![image](https://user-images.githubusercontent.com/6525576/150839896-0040b31c-db12-40d6-ab7c-e33d8db5905f.png)

We use the same font size and position as the "in cart" message, **the only difference is the color which should be #E54E47**.

5. One the shopper starts to add items to the cart, the message disappear and the "in cart message" is displayed. The "+" sign get disabled once the shopper's reached the stock limit (same current behavior)


*Scenario 2 : the feature stays disabled*

1. Log in as enterprise with shopfront
2. Check the feature is disabled by default
3. Check that no messages appear on the shopfront for variants with 3 on_hand value or less.

**Comment by RachL** [comment]
Issue created to avoid transfering the whole comment section: https://github.com/openfoodfoundation/openfoodnetwork/issues/8790
