### ISSUE TITLE
When deleting a line item, make returning to on-hand stock optional

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/wishlist#150]
## What is the need / problem?

Suppliers on OFN are usually anticipating stock availability when they set up OCs.  Product is still in the field.   So it is often the case that their hopes did not materialize and sold products have to be removed from orders because they weren't available,  or were of poor quality,   etc.     When a manager (producer's own store,  or a hub they supply) removes a product from an order today,  it automatically returns to stock 'on-hand' in their product list,   or to inventory (if a stock over-ride is being used).     This makes the unavailable product  available for sale again.  This is a problem when:  (1) the supplier or hub is managing a very large product list so its easy to 'miss' this returned stock,  (2) the supplier is selling in multiple order cycles open at the same time or in close sequence.

## Which type of users does this problem affect (and how many, if known)?
Any enterprise opening an order cycle

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Suggested by @Matt-Yorkley  - When a user is cancelling an order we could show a checkbox (checked by default) with a message like "Restock Items: return all items from this order to stock". That way it's clear what's happening, and there's an option to not restock the items, if that's not what the user wants to do.

## Is Papercut or feature candidate?

_Add papercut or feature label to answer the question. If you are not sure, don't worry product team will cover :-)_

**Comment by RachL** [comment]
Papercut meeting notes : 

Confirmed papercut. BUT this will not handle the scenario of cancelling an order.

**Comment by tschumilas** [comment]
Do I understand correctly:   If I delete a product from an order -  I would see the notification that  that deleted items are returned to stock,  AND there is a notice that allows me not return the item to stock (so re-set the on-hand amount to 0?).

So,  if I cancel the whole order -    I think we want something similar to happen -   but its a little more complicated because there would have to be a list of products being cancelled.    If I cancel an order with carrots,   and with potatoes -  and I want the carrots to return to stock,  but I have no potatoes left so I want the potatotes  set to 0 on hand.

And now -  I'm also wondering what if the product is over-ridden in inventory?   Maybe we just want this return to stock or set to 0  choice to apply to product lists,  and ignore inventory?    

Funny how what seems like a simple thing can get complicated - eh?     Maybe this is just simple now -  applies only to product list,  and only when an individual variant is removed from an order.   So no application to overrides,  and no applcation when an entire order is deleted.

??

**Comment by RachL** [comment]
Yes this is already borderline as a papercut, if we add stuff it's definitely not a papercut anymore :(

**Comment by RachL** [comment]
Closing as I've rewritten the issue here: https://github.com/openfoodfoundation/openfoodnetwork/issues/8767
