### ISSUE TITLE
Simplify small hub management

### ISSUE THREAD

**Issue by seballot** [openfoodfoundation/wishlist#151]
## What is the need / problem?
IMHO the shop/hub creation/management could be facilitated for easy cases
There are various complex configurations in order to handle complex shops, but for simple ones it's a bit overwhelming cause they need to deal with this same complex configuration.
Would be nice to make it easy/simple by default, and add the ability to do advance configuration when it's needed

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_

Children issues :
#152
#153
#154

**Comment by RachL** [comment]
I'm closing here to focus on the children issues :+1:
