### ISSUE TITLE
Shopfront: make the filters visible when scrolling

### ISSUE THREAD

**Issue by seballot** [openfoodfoundation/wishlist#155]
Happy to implement this feature myself if agreed

## What is the need / problem?
When scrolling we cannot filter again

## Which type of users does this problem affect (and how many, if known)?
_- Shoppers_

## Potential solutions that will solve the problem ?
Make it fly :) i.e. when scrolling keep it visible always at the same place

**Comment by RachL** [comment]
This one is done, closing :)
