### ISSUE TITLE
Report: make them printable

### ISSUE THREAD

**Issue by seballot** [openfoodfoundation/wishlist#156]
Happy to implement this feature myself if it's agreed

## What is the need / problem?

I want to print some reports (mostly the packing report), but for that I need to save it first as CSV and print it, with does display very nice :)

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem ?

Use the same nice table that is created when sent by email or when displayed in the browser, but make it printable. Two ways :
1. Adds ability to download as PDF
2. Adds Print button, and hide everything except the report table when printing (it's doable with css)

**Comment by RachL** [comment]
@Matt-Yorkley what do you think? Is it a good move to work on this on parallel of our reports improvements?

**Comment by RachL** [comment]
I'm closing as this will be fixed by the current work in https://github.com/openfoodfoundation/openfoodnetwork/pull/9032
