### ISSUE TITLE
[API] List all customers that the user has access to for all their enterprises

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/wishlist#165]
## What is the need / problem?

In FR we need to be able to fetch customers tags via the API. The customer endpoints are not yet define in OFN API so this wishlist is here to agree on a first version so FR can work on the endpoint that was started as part of https://github.com/openfoodfoundation/openfoodnetwork/pull/8326

## Which type of users does this problem affect (and how many, if known)?

_- Hub Managers (MCFEs)_
_- Instance Managers_

## Potential solutions that will solve the problem  ?

Proposal : 

RQ Params:
_Nothing additional to the standard rq queries_

RS Attributes:
Id - integer
Enterprise_id - integer
First_name - string
Last_name - string
Code - string
Email - string
Allow_charges - binary (NO CREATE OR UPDATE)
Tags - array of strings
Billing_address - address object. I believe this needs to be defined
Shipping_address - address object. I believe this needs to be defined
Terms_and_conditions_accepted_at - datetime (NO CREATE OR UPDATE)

**NOTE This field will not be added in the first iteration of this endpoint as there are significant performance considerations**
Customer_balance - double (ON SHOW ONLY) (NO CREATE OR UPDATE)

Scoping:
List all customers that the user has access to for all their enterprises.

Standard Acceptance Criteria around documentation and controller actions as described [here](https://community.openfoodnetwork.org/t/api-api-v1-discussions-from-the-portugal-delivery-team-mini-gathering/2456).
## Connected wishlist and discovery discussions

https://community.openfoodnetwork.org/t/api-api-v1-discussions-from-the-portugal-delivery-team-mini-gathering/2456/3

## Is Papercut or feature candidate?

Funded feature.

**Comment by kirstenalarsen** [comment]
* Can this take Enterprise_ID so that they can request only for a particular enterprise
* Do we have an estimate / quote on this?
Aus may well be willing to pay . .

**Comment by lin-d-hop** [comment]
Hi @kirstenalarsen 
As 'standard' the RQ params for all endpoints will include all the uncalculated results fields with some additional calculation options such as:
- datename_lt = dates less than the date
- datename_gt = dates greater than the date
- stringname_startswith = the string starts with the specified string
- stringname_con = the string contains the specified string

And much more. We don't have to do anything to get this functionality. @Matt-Yorkley can you link to any documentation that might explain this more? Even if its messy tech docs I think that would be easier than trying to type out what is meant by 'standard RQ params' every time someone wants to ask a question like 'can we search with xyz field'. :pray: 

No estimates on this yet.

**Comment by lin-d-hop** [comment]
Note when we create the epic we need to:
- Put https://github.com/openfoodfoundation/openfoodnetwork/issues/8577 as a blocker
- Split into two issues with Customer Balance as a separate issue to be completed later.

**Comment by lin-d-hop** [comment]
Also to note that https://github.com/openfoodfoundation/openfoodnetwork/pull/8326 makes a good start at this endpoint

**Comment by kirstenalarsen** [comment]
Thanks @lin-d-hop , my learning curve will be steep and I will be annoying for a while but hopefully it will be worth it

**Comment by Matt-Yorkley** [comment]
You'll be able to use these matchers when searching or filtering: https://github.com/activerecord-hackery/ransack/#search-matchers

So in this case for customers, you can use `enterprise_id_eq = 5` to get customers for enterprise 5.

**Comment by lin-d-hop** [comment]
Closing as superceded with https://github.com/openfoodfoundation/wishlist/issues/167 using the new FF template

**Comment by lin-d-hop** [comment]
Closing as superceded with https://github.com/openfoodfoundation/wishlist/issues/167 using the new FF template
