### ISSUE TITLE
Discount for Customers at Checkout 

### ISSUE THREAD

**Issue by devtdr** [openfoodfoundation/wishlist#166]
## What is the need / problem?
The possibility to provide a discount for (registred)-customers at the checkout.

## Which type of users does this problem affect (and how many, if known)?

_- Shoppers_

## Potential solutions that will solve the problem  ?

In the customers-section , a input field for discount in percent (%)
![discount](https://user-images.githubusercontent.com/26711236/145569964-962190cd-9d50-4c84-98d1-b4efb5218386.png)

**Comment by devtdr** [comment]
Please close this Issue, found a possible solution: https://guide.openfoodnetwork.org/hub-management-tips/how-tos/reward-your-volunteers

**Comment by tschumilas** [comment]
Just a quick FYI @devtdr  -  another option is to tag the customers who need the discount,   and tag them to an order cycle (a shop) versus payment method.  So this will create a separate storefront that only those tagged customers see.  Then you can have a negative enterprise fee (discount) on all products in this store.    Its just a question of optics maybe -  with a payment method discount the costomers see it at the end of their order.    But if you are offering multiple payment methods -  then you need to duplicate them all to offer each with the discount.   And if you have different discount levels -  its more duplication.... With a negative enterprise fee in the shop -  the customers see the price already discounted -  and then see the details of the discount if they click the pie chart.   so they see the lower prices when they are shopping -  which might affect their shopping behaviour.  And - you can easily have special produccts that only these people see too....    Just fyi.
