### ISSUE TITLE
Suppliers can edit their products on a hub's order

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/wishlist#172]
## Description
As a supplier,  I am currently able to edit my products and add/delete my products in an order cycle created by a hub I sell through.  And,  I can get a report on my products' sales through the hub.     BUT I cannot add or delete my products to an order received by the hub.

As a supplier,  I want to be able to add or delete my products on an order received by a hub I sell through.   

Use case:   Hubs are moving to contact-less pickups and are under-resourced to do this.  Most hubs are asking suppliers to do more of the packing and order organizing.   Today,  as a supplier of variable weight items,  I have to write a list of all the weights of the products,  and send these to the hub,   who needs to enter them into each customer's order.   It would be more efficient if, 
 as the supplier,  I could enter the weight directly into order using BOM as I weight out the items.

Use case:  Suppliers will soon be able (with the hub's permission)  to pre-pack orders by customer.  But today,  if something I offered is not available,  I must tell this to the hub,  who has to have someone change the orders.   It would be more efficient if, 
 as the supplier,  I could delete any of my items that are not available using BOM  myself.
In many situations,  hubs are under-staffed and are asking suppliers to pre-pack orders.

## Acceptance Criteria & Tests

The supplier should only be able to edit, add, delete their OWN products in BOM.
The supplier should not be able to make other adjustments to orders,  or change/view payment status, etc.  of an order.

1. Supplier can adjust the weight of a variable weight item -  for their products only -  using BOM
2. Supplier can delete one of their items from a hub's order  - using BOM
3. Supplier can add a new item item to an order - using BOM.

**Comment by RachL** [comment]
New issue here https://github.com/openfoodfoundation/openfoodnetwork/issues/13031
