### ISSUE TITLE
Group products by supplier in invoices

### ISSUE THREAD

**Issue by RonellaG** [openfoodfoundation/wishlist#185]
There are separate papercuts for delivery of this item. When #8968 and #8969 are complete then this is. All Devs, Product and Testing please use Clockify project [185](https://github.com/openfoodfoundation/wishlist/issues/185) Group products by supplier

## What is the problem we are solving 

One of our hubs, Strathbogie Local (ID#2840), packs a significant amount of orders each week.

The hub manager uses two things when they are packing produce:

1. The invoice goes on the front of the order box, because it has all of the customer details including phone number if there are issues with pick up.
2. The Pack By Producer list, and they work from heaviest producer through to lightest producer. As they place an item into a customer box, they tick off the item, to ensure they are cross checking every order.

**The problem is that items are listed in alphabetical order by product name in the invoice instead of being grouped by supplier.** 

Therefore, when the hub manager goes to to check off an item on the invoice, it is not easy to find the item and wastes time.

For example, the hub manager might be holding three bags of different tomatoes, and have to search through sometimes a very long list of items to find the three different product names, it would be incredibly helpful if there was an option in Shop Preferences the hub manager could select to sort products alphabetically by producer, and then by product name in invoices. ie:

Apples- Murrnong
Figs- Murrnong
Cherry Tomatoes- Ross Tomatoes
Truss Tomatoes- Ross Tomatoes

## Success factors = expected outcome 

When an invoice is generated for a customer, the items are sorted by supplier first and then alphabetically.

**Comment by kirstenalarsen** [comment]
Two additional notes as discussed with @RachL 

- there are two invoice templates. At this stage we are only proposing that this be implemented on the 'standard' one (the 'alternative invoice' setting in super-admin is OFF). I will post to instance managers to see if users of the alternative invoice would also like this
- Risk of this change disrupting packing processes is great, so we are proposing to make it a choice. 

We think the best spot for this is in Settings, Business Details, Create a new sub-section under 'Business Details' called 'Invoice Settings' and move all the bits relating to invoices (including this new switch) in there

![image](https://user-images.githubusercontent.com/2911176/155126111-beb89dbd-c835-4f16-bd61-d10163164697.png)

(dodgy image mock-up is [here](https://docs.google.com/presentation/d/1jgiqASf6VT8WjJOb40vMU6pvJgRgSORK-DZCJes3Zps/edit#slide=id.g116291497f6_0_13) if anyone needs to edit it)

**Comment by kirstenalarsen** [comment]
@RachL is that roughly what you meant by introducing a 'switch' component . . open to @jibees thoughts on this proposal

**Comment by kirstenalarsen** [comment]
NB. This is a potential funded feature - we have a user open to paying for it if we can get an estimate together and it is reasonable

**Comment by sigmundpetersen** [comment]
Just noting here that there's been discussion and initiatives on converging the two invoice templates and possibly bringing them together in the future. 

Not saying this needs to be implemted in both here, just noting it for consideration 😉

**Comment by kirstenalarsen** [comment]
Yes Rachel and I had same discussion! But shied away from trying to take that on . .

**Comment by kirstenalarsen** [comment]
Thanks @tschumilas - I can definitely see the value in working through that, but I'm not going to do so at this point :)

Just updating conversations from Slack thread [here:](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1645531123218799
)
- yes we definitely need the switch 
- there is interest in having it done for the alternative invoice as well, but not fair to ask Aus user to pay for that. Please estimate 
a) just doing the standard invoice template
b) how much extra to do the alt one

**Comment by mkllnk** [comment]
### Estimates

Did we clarify if sorting by producer is maybe useful for everybody?

* Just changing the sort order is a 10 minute dev job. Then adjust specs etc... an hour dev time, let's say. -> papercut
* Changing both invoice templates at the same time adds only 5 minutes of dev time. They currently use exactly the same sorting and whatever we do, we can just copy and past that in the other template.
* We can add a *feature toggle* to enable instances to try this out for all users. 1 hour work. -> papercut
* We can add a feature toggle per enterprise owner (we need a user). So all invoices of enterprises of that user would use the new sorting. Also an hour work.
* If we go the feature toggle way, we can experiment with this being the new standard and if nobody complains, we don't need the option in enterprise settings.
* Adding the enterprise setting: half a day. Borderline papercut. Could blow out a bit with refactoring, re-organising tabs.
* Alternative to the enterprise setting: add option to bulk printing of invoices. Customers still get the old invoice via email but the hub can choose how to sort the items when printing, depending what for. Similar effort to the enterprise setting but more flexible. Could also be confusing though.

#### My conclusion

Feature toggle for alternative sorting should be 2 hours max and is a papercut. Adding the enterprise setting could be a papercut, may blow out and could be covered as funded feature but if that's not necessary then we can keep the UX and codebase simpler.

**Comment by kirstenalarsen** [comment]
Awesome! So @mkllnk can I clarify that having the feature toggle per enterprise owner is included in the 2 hour estimate? I think we would definitely want that for bringing it in - not sure if it is 'either or' or 'both' re. feature toggles. Would we just have both set up? So that we can bring users across progressively and then just switch it once we're sure everyone's ok?

**Comment by mkllnk** [comment]
Yes. The limitation is that we can't do it per enterprise, only per enterprise owner. So all invoices of enterprises owned by the user it's activated for will have the different sorting.

**Comment by kirstenalarsen** [comment]
I think that's fine - ace. So this can be approved as an Aus papercut - yippee!

**Comment by kirstenalarsen** [comment]
Please use Clockify project #185 Group products by supplier
