### ISSUE TITLE
Allow order cycle to be changed for complete orders

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/wishlist#192]
## Description

Orders with status = complete cannot have their order cycle changed.

## Expected Behavior

Order cycles should be adjustable, regardless of order state.

## Actual Behaviour

The order cycle field is only editable when in the status = payment. The dropdown to change it disappears once in status = complete.

## Steps to Reproduce

1. Go to the orders view and view or create an order where state=complete (i.e. enter payment information)
2. Try to change the order cycle from the order details screen and see that the order cycle value is fixed (no dropdown present)

## Animated Gif/Screenshot

Screenshot showing order in complete state with dropdown missing meaning order cycle cannot be edited.
<img width="1220" alt="Screenshot 2022-03-07 at 13 04 13" src="https://user-images.githubusercontent.com/100226210/157041056-7bdf9b6f-d40c-41d0-9fba-564ef2bb9a13.png">

## Workaround

The workaround is to cancel the order, which allows for the order cycle to be changed, and the order can then be resumed. Alternatively cancel and recreate the order.

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: UK prod
* Browser name and version: 
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment]
Fees and adjustment are linked to OC, so it can be tricky to recalculate on a completed order.

@BethanOFN can you share information on your use case? When do you need to change an OC on a complete order?

**Comment by lin-d-hop** [comment]
This comes up semi-regularly that a shopper places an order and then realises they are away or something cant be delivered until next week and the hub would find it easiest to just change the order to next OC. However the complexity that this will entail from a dev perspective is really not worth the gain to the platform. I think we can close this.
