### ISSUE TITLE
[API for shopfronts] Refactor OFN shop list to use API for add line items to cart

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/wishlist#199]
## Description
Spree 2 has changed order.add_variant and a few more things in Order and OrderPopulator. See the [checkout customizations wiki page](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Spree-Upgrade:-Checkout-customisations) for context.

We propose to move away from extending Spree code order_decorator and order_populator_decorator and re-implement this logic in OFN.
So, there should be a new API endpoint for /cart that will take (to be confrmed): order_id, line_item_id and quantity. This will be implemented in Api::CartController. This controller should depend on new OFN service class CartService. This service will implement what's currently in order and order_populator and will depend, but not extend, Spree classes. Basically, what's in  orderpopulator.populate and order.add_variant needs to be moved and adapted.

This change must be done on OFN master branch (so that we can validate and test easily) and then merged back to spree branch.

Additionally, and to support the upgrade to spree 2.1, we should move away from order.add_variant and use add_contents instead. This can be done later. If we make the code depend on order.add_variant we can then simply move from add_variant to add_contents.

Additionally, if not too difficult we would change the frontend to stop making bulk calls with groups of line items and make one call per line item. We can keep current API with bulk to make it easier for now.

## Testing

It's a technical change, there should be no UX change in the add to cart process.

**Comment by mkllnk** [comment]
This issue was related to a Spree upgrade which is finished. The code changed a lot since and I think that this issue is obsolete. Closing.
