### ISSUE TITLE
Receive feedback/confirmation after cancelling an order as a customer

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#216]
## What is the need / problem?
As a customer I would like to receive feedback when cancelling an order in my account. This includes:
- _receiving the cancellation email (this is implemented already)_ AND
- a flash message on the screen after confirming that I want to cancel the order AND
- seeing the state 'cancelled' (or 'confirmed' if not cancelled) in the list of 'past orders' in an additional column

## Which type of users does this problem affect (and how many, if known)?
- Shopper

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Add
- a flash message on the screen after confirming that I want to cancel the order AND
- seeing the state 'cancelled' (or 'confirmed' if not cancelled) in the list of 'past orders' in an additional column

## Connected wishlist and discovery discussions* [list precedent discussions]
https://github.com/openfoodfoundation/openfoodnetwork/issues/8806#issuecomment-1095227780

## Is Papercut or feature candidate?
Let me know if this should be split into two separate items to make them papercut size.

_Add papercut or feature label to answer the question. If you are not sure, don't worry product team will cover :-)_

**Comment by RachL** [comment]
Proposal :

- Replace the "view" column by "status" column, 
- Add a link on confirmed status only, to view the order.
- Remove links from order numbers
- Add a flash error after cancelling

This way we fix the error 500 on viewing cancelled orders. cancelled orders would not be available for expanded view.

Papercut confirmed, to be rewritten properly.

**Comment by filipefurtad0** [comment]
> This way we fix the error 500 on viewing cancelled orders. cancelled orders would not be available for expanded view.

This came from my confusion with another bug #5505 - viewing cancelled orders don't generate error to the customer, but empty orders do (-> which I think we can close now).

**Comment by RachL** [comment]
new issue created here: https://github.com/openfoodfoundation/openfoodnetwork/issues/9304
