### ISSUE TITLE
[API] Add Balance to Customer Endpoint

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/wishlist#218]
## What is the need / problem?
The last field to complete the customers endpoint is customer balance.

This field is tricky as it is calculated for each customer as requested. The calculation involves iterating through every order for that customer, so a query that retrieves a set of customers with their balances will have significant performance implications.

This field will not be updateable and will be zero on create:
Customer_balance - double (ON SHOW & INDEX behind param) (NO CREATE OR UPDATE)

This field will display on /show
This field will need to not display by default on /index. We'll need to hide it unless specifically requested in the request eg including a param like display_customer_balance

## Which type of users does this problem affect (and how many, if known)?
_e.g._
_- Hub Managers (MCFEs)_

## Connected wishlist and discovery discussions* [list precedent discussions]

Related to #167 

## Is Papercut or feature candidate?

Maaaybe a papercut...?

_Add papercut or feature label to answer the question. If you are not sure, don't worry product team will cover :-)_

**Comment by lin-d-hop** [comment]
Note if this is a papercut then UK will select it.
If not UK would like to schedule this as a funded feature.

**Comment by RachL** [comment]
@lin-d-hop it's already considered as a papercut: https://github.com/openfoodfoundation/openfoodnetwork/issues/8909
