### ISSUE TITLE
Link payment methods to shipping methods

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/wishlist#229]
## What is the need / problem?

Some users have a lot of shipping methods and payments methods per shop. They would like to combine them: when selecting one shipping method, only a subset of payment methods would then be available for the shopper.

For example, we have a lot of hubs who do bike delivery alongside pick-up at the shop. In this case they want all their shoppers who get delivered to pay exclusively by credit card.

Currently they write in the name of the payment method "please use this payment method if you want to be delivered". Which does not work all the time.

## Which type of users does this problem affect (and how many, if known)?

_- Shoppers_
_- Hub Managers (MCFEs)_

## Is Papercut or feature candidate?

Dunno

**Comment by lin-d-hop** [comment]
Could this be handled at the Order Cycle level if we had better OC management? I get the admin on OCs is limiting at the moment to creating many OCs with slightly different configurations.

I worry that this would add such complexity to relationships that UX would be a nightmare... Trying to find why a payment/shipping method isn't showing when we have so many ways it can be turned on and off will be hard :sweat_smile: 

I think it's worth taking some inception time on different ways this could be solved....

**Comment by RachL** [comment]
@lin-d-hop yes there will be different solutions (tags, selection on the shipping method in admin...). But I'm not sure OC will be a good idea: in the cases we have, all shipping options are available on the same OC. They could do different OC but often these users have already 2 to 4 OC because they handle also different prices / products etc... 🤯 

Deff needs an inception, but I wonder also if some solutions could be papercuts?

**Comment by RachL** [comment]
Actually a duplicate of https://github.com/openfoodfoundation/wishlist/issues/76 closing here
