### ISSUE TITLE
Reputation system

### ISSUE THREAD

**Issue by diegoamc** [openfoodfoundation/wishlist#230]
## What is the need / problem?

- It would be nice to have a reputation system for producers and consumers

## Which type of users does this problem affect (and how many, if known)?

- Shoppers
- Producers

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

There's an open source gem that provides many features we can use
- https://github.com/merit-gem/merit

**Comment by diegoamc** [comment]
I saw that in the past OFN has considered recommendations and ratings features (https://community.openfoodnetwork.org/t/product-roadmap/80). I could not find any further discussion on this topic, though. Was these features dropped from the roadmap for some reason?

**Comment by RachL** [comment]
hello @diegoamc yes this was dropped as we had more urgent things to do and there was also a lot of debate on this. Is it something we want to introduce: comparison between our users? what do you think?

**Comment by diegoamc** [comment]
Hi @RachL , I've discussed the matter with our internal team and stakeholders and we agree that it would not be a good idea in OFN's context.

Thanks!

**Comment by RachL** [comment]
@diegoamc thank you for the feedback. I will close this one then. But we can always reopen if needed.
