### ISSUE TITLE
Reports: Enable optional summary rows for CSV files

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#238]
## What is the need / problem?
It was agreed [here](https://openfoodnetwork.slack.com/archives/C012LE8LLDS/p1654848108028799) that adding optional summary rows in exported csv reports is not a fix for this bug [#9291](https://github.com/openfoodfoundation/openfoodnetwork/issues/9291), but a wishlist item instead.
Some users have created scripts around the csv files which used to have the summary rows, before the major reports changes in [#9032](https://github.com/openfoodfoundation/openfoodnetwork/pull/9032).
As on other output formats, the creation of summary rows should be optional, using the already existing checkbox for that setting.

![grafik](https://user-images.githubusercontent.com/1790176/173065068-771ec576-89c6-4443-a283-c3dfd348e92f.png)

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Instance Managers

## Potential solutions that will solve the problem?
- Add the summary rows in the same way as they are used for the formatted data options (on screen, pdf, spreadsheet).
- Make sure to remove the greying out of the summary row checkbox and the explaining text around this (in case the bug has been fixed in the meantime).

## Connected wishlist and discovery discussions
https://openfoodnetwork.slack.com/archives/C012LE8LLDS/p1654848108028799
https://openfoodnetwork.slack.com/archives/C018S101R4J/p1653616976562189
https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1653906673754279
https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1653536874661149
https://github.com/openfoodfoundation/openfoodnetwork/pull/9032#issuecomment-1109913421

## Is Papercut or feature candidate?

_Add papercut or feature label to answer the question. If you are not sure, don't worry product team will cover :-)_

**Comment by RachL** [comment]
As per this comment: https://github.com/openfoodfoundation/openfoodnetwork/issues/9291#issuecomment-1180432825 it won't be possible to do it. Closing.

https://github.com/openfoodfoundation/openfoodnetwork/issues/9291 will handle a proper solution
