### ISSUE TITLE
Enable webp images for products (again)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#245]
## What is the need / problem?
Along with [#9301](https://github.com/openfoodfoundation/openfoodnetwork/pull/9301) webp image format was removed from the white list of supported image types only a short time after it was introduced by [#9303](https://github.com/openfoodfoundation/openfoodnetwork/pull/9303). Maybe we should enable this option again.
Bmp and tiff image format are not well suited for the web and probably don't need to be added again.

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers

## Potential solutions that will solve the problem?
Add webp to the white list of supported image formats.

## Is Papercut or feature candidate?

_Add papercut or feature label to answer the question. If you are not sure, don't worry product team will cover :-)_

**Comment by RachL** [comment]
Unless we are wrong this is already fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/9440
 we can reopen if it's wrong
