### ISSUE TITLE
Minimum order spend

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/wishlist#253]
## What is the problem we are solving
To be efficient, shops often need their orders to be of a minimum value at least. Orders received below this value may actually lose the shop money, or reduce their margin. 
Currently there's no way for shops to set a 'minimum spend' in their shop. In the absence of such functionality shops either need to absorb the inefficiency of low value orders, or have an awkward conversation with a customer - which is not great for customer relationships

## Success factors = expected outcome 
Shops can avoid receiving orders that are below their minimum threshold. Customers are aware of this requirement and aren't surprised.

## Metric
- Can shops automatically prevent orders below a given minimum value? 

## Link to the "Product Development - Backlog" item in Discourse
https://community.openfoodnetwork.org/t/shops-can-require-a-minimum-spend-before-customers-can-checkout/1350

## First feature candidate to be implemented
This needs further discussion. One suggestion here:
- Shops can set an optional 'minimum spend' value in their settings. This minimum spend requirement is communicated clearly to customers in the shopfront. If the customer tries to checkout with a cart below this value they're reminded of the minimum value requirement and redirected to the shopfront.

**Comment by audez** [comment]
included in https://github.com/openfoodfoundation/wishlist/issues/254
