### ISSUE TITLE
Implement new design for backoffice

### ISSUE THREAD

**Issue by seballot** [openfoodfoundation/wishlist#255]
This new design has been approved and needs to be implemented

https://www.figma.com/file/UOUOI0AdaL3gRmZWacHnsO/OFN-Color-Choice?node-id=2%3A627

I will start working on it soon

This design include ability to select multiple products and do bulk actions, but this should be a dedicated feature (or maybe it's a pending PR?)

**Comment by RachL** [comment]
This is in progress with some design changes and will be released along Product Back Office UI Uplift. A communication will be issued on the forum when this is ready to beta test. 

Closing here :)
