### ISSUE TITLE
[Reports] Adding SKU column to Orders & Fulfillment Reports

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#259]
⚠️ before starting this papercut we need to ask instance managers if they use this field in integrations.

## What is the need / problem?
One of our biggest wholesaler would like to have the SKU displayed in the [Orders and Fullfilment](https://coopcircuits.fr/admin/reports/orders_and_fulfillment) reports.  

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Additional context
The need is to have a report with all orders info, including SKU, by distributor. This would be possible in the [Orders And Distributors](https://coopcircuits.fr/admin/reports/orders_and_distributors) report, but there is no filter "by distributor" (requested in #258)

## Potential solutions that will solve the problem  ?
Displaying the products SKU in the "Orders and Fullfilment" reports:
![Screen Shot 2022-08-10 at 10 49 24](https://user-images.githubusercontent.com/28386648/183858491-35e30dfd-dc90-44b7-8c60-7acb677d9bf8.png)

**Comment by RachL** [comment]
As #258 is a papercut, we will close this one for now. Let's see if it's needed in the future we can reopen it.
