### ISSUE TITLE
[Products] Choose category inline, directly from the products list 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#266]
## What is the need / problem?
The category field is a commonly used field, but is not available for direct inline edition in the products list. It makes the process of product cloning/editing longer and strenuous. 

## Potential solutions that will solve the problem 
Adding a column "Category" in the products list, as proposed in the new design of the product list ([ Backoffice Product List table UI uplift 7198](https://github.com/openfoodfoundation/openfoodnetwork/issues/7198)). 

![product list - category](https://user-images.githubusercontent.com/28386648/186502624-82809027-cfa0-49ef-8cd7-568da81a8439.png)

## Connected wishlist and discovery discussions

[ Backoffice Product List table UI uplift 
7198
](https://github.com/openfoodfoundation/openfoodnetwork/issues/7198)

## Additional context
Some users complain that it's very long to create products. We advise them to use the spreadsheet for bulk import, but it also takes time to understand the spreadsheet columns and have a file ready for import without errors. 
It would be great to have a fast and easy way to create products from the interface.
This + #264 and #265 could help fasten and ease the process.

**Comment by RachL** [comment]
@audez you can already have category as an available field /column by clicking on the column button - selecting category and choosing this as the default view. Is that what you were looking for?

**Comment by RachL** [comment]
Closing in the meantime.

**Comment by audez** [comment]
oooh ok, yes, that's what i was looking for! thanks
