### ISSUE TITLE
Allow users to turn off email notifications

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#277]
## What is the need / problem?
Some hubs or shop owners don’t want an email notification for every order, that are clogging their inbox. They would like to deactivate notifications.

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Add the possibility to choose nothing in the "Notifications" dropbox
or
Add a button "Notifications : ON/OFF" or "Turn off notifications", either in the Users tab or in the Shop preferences (if we want it to be more hidden), then if notifications are turned off, grey out and disable the notifications dropdown list
or 
Allow only superadmin to switch off notifications for a user

## Additional context
https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1583373309071000

![Screen Shot 2022-09-15 at 13 55 05](https://user-images.githubusercontent.com/28386648/190398083-f47b38a9-7381-423b-9bcd-6f9001c44458.png)

**Comment by drummer83** [comment]
Is this a duplicate of #270?

**Comment by audez** [comment]
yes it is thanks :)
