### ISSUE TITLE
[Split Checkout] Consistent formatting of price for payment and shipping methods

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#280]
## What is the need / problem?
Prices of payment and shipping methods should be formatted consistently during checkout.
Currently the are formatted differently:
- Use spacing between name and price?
- Use brackets?
- Use italic font style?
- Use different font size?
- Use different font colors?
![image](https://user-images.githubusercontent.com/1790176/193088448-7f3983f5-3ef9-4a09-9d51-5fb39d495a6f.png)

## Which type of users does this problem affect (and how many, if known)?
- Shoppers

## Potential solutions that will solve the problem
My favourite would be to use the styling of shipping info for payment methods as well. In my opinion with this solution it is quicker to identify the price.

**Comment by RachL** [comment]
This is taken into account in new split checkout design :+1: which is going in development soon. Closing here.
