### ISSUE TITLE
[Admin] Replace old dropdowns with the new 'multiple checked select component'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#291]
## What is the need / problem?
In [#9706](https://github.com/openfoodfoundation/openfoodnetwork/pull/9706) the new multiple checked select component was introduced. This component can and should be used throughout the entire admin area.

![Peek 2022-10-08 16-06](https://user-images.githubusercontent.com/1790176/194711609-14b50b7a-638d-4a04-825c-847f64484d5a.gif)

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers
- Instance Managers

**Comment by RachL** [comment]
This will be handled by Back Office Product UI Uplift :+1: Closing here
