### ISSUE TITLE
[Shop preferences] Improve "Display ordering in shopfront" feature

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#296]
## What is the need / problem?
A user regularly changes the ordering of producers in the shopfront. They use the "Display ordering in shopfront" feature, but as it's not possible to change the ordering or to click in between 2 elements, each time they have to delete everything and start from scratch.

edit: actually it's possible by drag&drop! But there's no indication that you can drag and drop: the mouse cursor when you hover the element is the standard arrow cursor (except when you hover the cross to remove the item).

current behavior:
<img width="838" alt="Capture d’écran 2022-11-23 à 23 40 59" src="https://user-images.githubusercontent.com/28386648/203662673-6384b032-f690-4cf5-b0e3-48c247803ee6.png">

<img width="853" alt="Capture d’écran 2022-11-23 à 23 41 09" src="https://user-images.githubusercontent.com/28386648/203659884-14ce4235-37ce-4075-bb96-f9c4401f19bd.png">

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?
We should add a hand-grab cursor icon when hovering the item. These icons are generally one of these two:
<img width="237" alt="Capture d’écran 2022-11-23 à 23 32 13" src="https://user-images.githubusercontent.com/28386648/203658504-ef39482e-6ebe-430b-af73-bc0e871060e6.png">

But we have to take into account that inside the element there's also the cross to remove the item, and when hovering the cross the cursor changes to a finger icon. 

I think about 2 things but there's certainly more/better (i can't find guidelines or best practices for drag&drop, but [this](https://www.nngroup.com/articles/drag-drop/) helped a lot and is where i found out the icons).

**Solution 1:**
 Putting a grab-handle icon on the right on the element and change standard arrow cursor to hand grasping only when cursor hovers this icon.

It would look like this:
<img width="505" alt="Capture d’écran 2022-11-24 à 00 04 17" src="https://user-images.githubusercontent.com/28386648/203661028-b91de7d2-6ac7-4152-89f5-2346b4e21c9c.png">

Ohter ex of grab handle icons: 
<img width="311" alt="Capture d’écran 2022-11-23 à 23 55 43" src="https://user-images.githubusercontent.com/28386648/203660128-42e8b950-f19f-4afb-af79-8b2a0bbc23e4.png">

**Solution 2:**
Remove the cross inside the element and allow the user to remove the item by dropping it out of the field - indicate this by the appearance of a cross, a trash icon, or a transparency thing..
<img width="574" alt="Capture d’écran 2022-11-24 à 00 17 19" src="https://user-images.githubusercontent.com/28386648/203662239-90a3e579-dc5f-4652-8a49-b754165fa597.png">

Change cursor to hand grasping when hovering any part of the item.

**Comment by RachL** [comment]
@audez on my side drag & drop is working. Did you manage to reproduce? If so on which browser?

**Comment by audez** [comment]
oh lala yes it works, didn't even try to drag and drop actually... i didn't think about it. The producer neither apparently..Maybe then we can add a small text "You can drag and drop to change the ordering"? 
That's cool!

**Comment by audez** [comment]
Eureka! i know why I (and the producer) didn't understand that we could drag and drop: it's because there's no cursor change. Normally, when an UI element is drag&droppable, when you hover the element with the mouse there's a cursor change indicating that clicking it will initiate a grab. 
The cursor icons are generally one of these two:

<img width="237" alt="Capture d’écran 2022-11-23 à 23 32 13" src="https://user-images.githubusercontent.com/28386648/203657430-5fbcd476-901b-49ec-bbbf-7ff526e3896d.png">

This is so silly but that can save lives 😂
I'm editing the issue, hope this can be a papercut 🙏

**Comment by audez** [comment]
im actually closing because i ll write another one that encompasses another issue with this option
