### ISSUE TITLE
[Shopfront] Highlight allergens in product "short" description

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#297]
## What is the need / problem?
One of our producers had a safety control from a state organism, and they said that the allergens were not highlighted enough when seeing the products in the shopfront. There is indeed a UE law (Regulation No. 1169/2011) concerning consumer information on foodstuffs, which specifies that the presence of allergens must appear on the list of ingredients and be highlighted.

## Which type of users does this problem affect (and how many, if known)?
_- Shoppers_
_- Hub Managers (MCFEs)_
_- Producers_
_- Instance Managers_
_- Other (Please specify)_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
For now, when a producer set bold text in the product description, the bold text doesn't appear in the short description, but only in the description modal. Clients don't always click on the product details, so they won't see the highlighted allergens.

The solution could be to display bold text in the short description too.

## Modal
![Screen Shot 2022-10-13 at 14 39 55](https://user-images.githubusercontent.com/28386648/195599497-9cdaf8b8-5c84-4073-82a1-4f86fc79028c.png)
## Short description
![Screen Shot 2022-10-13 at 14 39 47](https://user-images.githubusercontent.com/28386648/195599508-89ba65cd-3e55-4949-84df-7050462db205.png)

**Comment by RachL** [comment]
Moved to https://github.com/openfoodfoundation/openfoodnetwork/issues/10211

Closing here
