### ISSUE TITLE
[Reports] Add SKU column to "packing" and "orders and fulfillment" reports

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#314]
## What is the need / problem?
SKU are missing from the "packing" and "orders and fulfillment" reports. It's compulsory to have it for at least one of our suppliers. For now hey use the report notification mail, but one of their distributor doesn't want to send it because it would send it to all of the suppliers.. So they're stuck.

For now there's no equivalent to the notification mail report. Having SKU in the "packing" report would allow users to have an alternative, by hiding unnecessary columns. The report would still be less intuitive and more difficult to read than the mail one, but it would already be cool. 

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
 Add SKU column to "packing" and "orders and fulfillment" reports

## Additional context
**Mail notification report**
![Screen Shot 2022-10-24 at 16 33 39](https://user-images.githubusercontent.com/28386648/198119780-32c74d51-3498-4b30-8128-e31bffbcf610.png)

**Packing report**
![Screen Shot 2022-10-26 at 21 27 40](https://user-images.githubusercontent.com/28386648/198119811-4a22e5da-1bea-4fbe-b65e-2eb08e38add0.png)

**Orders and fulfillment report**
![Screen Shot 2022-10-26 at 21 27 18](https://user-images.githubusercontent.com/28386648/198119825-39eb8dc6-695e-4d5c-809f-5b5004be7784.png)

**Comment by RachL** [comment]
Closing as the main need is handled by https://github.com/openfoodfoundation/openfoodnetwork/pull/10040
