### ISSUE TITLE
[Admin] Business Details: Add placeholder for Country and State dropdowns and include in validation

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#315]
## What is the need / problem?
On page Business Details (/admin/enterprises/_ENTERPRISE_#!#business_details_panel) the first available country and state are preselected by default. It would be better to have a placeholder instead and if no Country or State is selected, the error message for missing information should be shown (the same as if legal name or legal address is left empty). Also required fields should be marked with the red asterisk (like on page Address).

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers

## Potential solutions that will solve the problem
- Add a placeholder 'Select country' to Country dropdown
- Add a placeholder 'Select state' to State dropdown
![image](https://user-images.githubusercontent.com/1790176/196990673-1f2aabf8-c6de-416d-8015-430556682cec.png)
- Add the remark 'Required fields are denoted with an asterisk ( * )' from page address above 'Company Legal Name'
- Mark the following fields as required using the red asterisk
  - Company Legal Name
  - Legal Address
  - City / Postcode
  - Country / State
  - Legal Phone
![image](https://user-images.githubusercontent.com/1790176/198289901-05c8c9ea-9966-41d1-b763-ac1d736e91bf.png)
- If any of the required fields is 'not empty' on submission, then show the error message 'xy can't be blank'. This working already for all fields except for 'Country'.
![image](https://user-images.githubusercontent.com/1790176/198289468-ddce417a-c062-4a47-b835-5cdf177a3dab.png)
- If 'reset Form' is clicked, empty all fields and set Country and State back to the placeholder.

## Connected wishlist and discovery discussions
https://github.com/openfoodfoundation/openfoodnetwork/pull/9780#issuecomment-1291769683

**Comment by RachL** [comment]
Papercut but needs to be cut in several issues :+1:

**Comment by RachL** [comment]
issues : 

https://github.com/openfoodfoundation/openfoodnetwork/issues/10270

https://github.com/openfoodfoundation/openfoodnetwork/issues/10271

I didn't create one for Add the remark 'Required fields are denoted with an asterisk ( * )' from page address as I think we should actually remove that sentence. Asterisk are well know on the web now? If so we can handle the removal during Admin v2 styles
