### ISSUE TITLE
Payment failure can lead to server error

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/wishlist#33]
## Description

When an admin creates an order and the payment fails, the error message can't be translated and it leads to a server error.

## Expected Behavior

The error message is displayed:

> Payment could not be processed, please check the details you entered

## Actual Behaviour

I didn't test this but a server error is generated.

## Steps to Reproduce

0. You need a customer with an invalid stored credit card. Maybe one that expired?
1. Go to `/admin/orders`.
2. Click the capture button on an order for that user.

## Animated Gif/Screenshot

...

## Workaround

Update the credit card details.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
**bug-s3: a feature is broken but there is a workaround**
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment

* Version used: v3.5.5

## Possible Fix

Make the `I18n.t` method available in that API controller.

## Error in OpenFoodNetwork

**NoMethodError** in **api/orders#capture**
undefined method `t' for #<Api::OrdersController:0x0000559af50a41b0>

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/600fdac12fd5e3001891a818?event_id=600fe1f20069996de8d40000&i=gh&m=ci)

## Stacktrace

    app/controllers/api/orders_controller.rb:50 - payment_capture_failed
    app/controllers/api/orders_controller.rb:36 - capture

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/600fdac12fd5e3001891a818?event_id=600fe1f20069996de8d40000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by Matt-Yorkley** [comment]
I have a feeling this is already fixed...

**Comment by apricot12** [comment]
![image](https://user-images.githubusercontent.com/65319144/125097257-910aa200-e0f3-11eb-9d8f-90700d807b6c.png)
Seems to me what's required here is already done?

**Comment by mkllnk** [comment]
You are right. It was fixed in 5354c63d9a074a870ee7f75ad520fe49abd7628b by Matt. I checked Bugsnag as well and the error hasn't come up there.
