### ISSUE TITLE
[Invoices] Display weight/volume and initial unit price 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#391]
## What is the need / problem?
In the invoices, there's only columns "quantity" and "price per unit". For products of irregular weights/volume that are adjusted in BOM page, the final weight/volume is displayed in parenthesis after the line item name, and the displayed unit price is the price corresponding to the final weight/volume.

The need is to display a column "weight" and display the initial unit price (price per kilo for instance).  

## Which type of users does this problem affect (and how many, if known)?
_- Shoppers_
_- Hub Managers (MCFEs)_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

The following example is a product that costs 10€/kg, but weight is irregular. 

<img width="1180" alt="Capture d’écran 2022-12-26 à 11 39 24" src="https://user-images.githubusercontent.com/28386648/209540983-47314133-c882-44ce-8b93-88d704a2db18.png">

For this order, the producer adjusted the weight in BOM page, the piece is finally 1,2kg.

### What is currently displayed in the invoice 
<img width="960" alt="Capture d’écran 2022-12-26 à 11 49 52" src="https://user-images.githubusercontent.com/28386648/209540773-c652d83d-f2bf-4b5b-b233-2c492e869b1a.png">

### What is needed
<img width="960" alt="Capture d’écran 2022-12-26 à 11 49 52(1)" src="https://user-images.githubusercontent.com/28386648/209540802-5d6f76e5-76c1-4e7a-8bed-9d6e79e90afd.png">

**Comment by RachL** [comment]
@audez 

> the displayed unit price is the price corresponding to the final weight/volume

In which cases does the unit price change? If the weight is changed in BOM, the unit price should remain the same.

**Comment by audez** [comment]
If you have an initial unit price of 10€/kg, as in the screenshot example, after you change the weight in BOM, the displayed unit price in the invoice is "12€" because it corresponds to 1.2kg (the weight that was changed in BOM). The need is to display the initial price and unit (10€/kg) and the weight (1.2kg) in another column

**Comment by audez** [comment]
A better way to display the unit price in this case might be to remove the weight in parenthesis and display it in the "unit price" column:

<img width="765" alt="Capture d’écran 2022-12-27 à 15 37 34" src="https://user-images.githubusercontent.com/28386648/209681978-ea7c508c-543a-4cfb-bc0a-ea51711b8efe.png">

**Comment by RachL** [comment]
Yep, so the unit price does not change. I asked because of this sentence:

> the displayed unit price is the price corresponding to the final weight/volume

Which I understood as "the unit price of the final weight is different from the unit price of the initial weight". My bad :+1:

**Comment by RachL** [comment]
And actually final weight in the new template too
