### ISSUE TITLE
Change word 'administration' on nav bar

### ISSUE THREAD

**Issue by Jesszahra** [openfoodfoundation/wishlist#393]
**It is unclear to new users how they can set up their shop and access their shop account. Once they sign up they should be able to easily find how to login and set up their shop account.**

This problem effects new hub managers and producers.

## Potential solutions that will solve the problem  ?

- Change the word administration to 'my shop' or similar wording

## Additional context
- This could be overhauled in the future so that shop owners have a separate login and never need to be able to buy from other shops. So it will remove all of the clutter and allow them to concentrate on managing their shop. But for now, a simple fix of language should help people understand where to go.

**Comment by RachL** [comment]
@Jesszahra hello! we can change the text in the OFN code base, but it won't change the text on live instances: even in English-speaking countries, each live production has it's own text file handled in a tool called Transifex. So if this in needed in Australia for example, the text can already be changed in transifex and can be live on the next release (releases happen every Tuesday).

**Comment by Jesszahra** [comment]
Yep OK sounds good. I will speak with the team when everybody is back and we can change it (for all English speaking countries?)
