### ISSUE TITLE
Close down login modal after sign up

### ISSUE THREAD

**Issue by Jesszahra** [openfoodfoundation/wishlist#394]
## What is the need / problem?

After sign up the login modal does not close. This is a problem as most password saving plugins such as chrome and last pass rely on the modal to be closed to trigger them to save the password. This will mean the user has to immediately click "forgotten password" after they sign up as (from memory) our site does not automatically log you in once you sign up. It also places a load on our servers for people clicking to retrieve password as they cannot use last pass or google.

This effects every single new user, and potentially other users if they haven't been able to save their passwords.

## Potential solutions that will solve the problem ?
Close down the login modal after sign up. Check that this will trigger password saving functionality.

**Comment by RachL** [comment]
- close the modal after sign-up
- display the success flash banner on the home page instead of within the modal

=> this is a papercut

**Comment by RachL** [comment]
I've opened https://github.com/openfoodfoundation/openfoodnetwork/issues/11597 closing here
