### ISSUE TITLE
Two arrows on dropdown

### ISSUE THREAD

**Issue by Jesszahra** [openfoodfoundation/wishlist#395]
<img width="165" alt="Screen Shot 2023-01-05 at 12 01 56 pm" src="https://user-images.githubusercontent.com/107977095/210678504-e3c47f16-a33c-465f-81e8-614c54ff9f87.png">

## What is the need / problem?
Two arrows are appearing on the dropdown in Enterprise settings. 

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?
Delete one of the arrows

## Additional context
This is not a huge deal but it is a bug that could be quick to fix and make things less confusing.

**Comment by Jesszahra** [comment]
<img width="1431" alt="Screen Shot 2023-01-05 at 12 04 24 pm" src="https://user-images.githubusercontent.com/107977095/210678663-da1b4b28-0fb3-4504-a86c-b11b8e4c14a7.png">

**Comment by RachL** [comment]
This will be fixed while doing the new colors work on the dropdowns :+1: closing!
