### ISSUE TITLE
Display a warning message when changing the date range of an OC with linked orders  

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#413]
## What is the need / problem?
To create a new OC, some users change the date range of an old one instead of duplicating it first. 
This has hard consequences: producers bringing too much food on the delivery day and a big mess with orders. 

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
When changing the date range of an OC which has linked orders, display a popup, for instance: "Orders are linked to this order cycle. If you wish to create a new order cycle, it is recommended to duplicate the order cycle first and then change the dates."

With two buttons as:
"Proceed anyway" -- "Cancel"

Here's the mock-up for guidance:
![image](https://github.com/openfoodfoundation/wishlist/assets/68649866/fa715024-31eb-4f9a-bf0e-2ff74ec311d4)

Here's the Figma link to the design:
https://www.figma.com/file/8iCdevuefE4hRIbGyBhWHX/Nicholas-Pushes?type=design&node-id=1%3A3&mode=design&t=seDLvGHNaCuVMQLs-1

**Comment by lin-d-hop** [comment]
Confirmed papercut :)

**Comment by lin-d-hop** [comment]
Eeep, I'm just writing this up as an issue and I'm retracting it as a papercut. It needs design work to figure out the best error message solution. Sorry!

**Comment by NickIkenma** [comment]
What does OC mean though?

**Comment by sigmundpetersen** [comment]
> What does OC mean though?

Order Cycle

**Comment by NickIkenma** [comment]
I did a design for this. Hope it helps!
![image](https://github.com/openfoodfoundation/wishlist/assets/68649866/d6b6c209-2d81-47c6-9da6-c23146c880fa)

Here's the Figma link to the design:
https://www.figma.com/file/8iCdevuefE4hRIbGyBhWHX/Nicholas-Pushes?type=design&node-id=1%3A3&mode=design&t=seDLvGHNaCuVMQLs-1

**Comment by RachL** [comment]
hopla: https://github.com/openfoodfoundation/openfoodnetwork/issues/11613

closing here
