### ISSUE TITLE
[Reports] Add "product" filter in Orders & Fulfillment 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#418]
## What is the need / problem?
In  Orders & Fulfillment reports, a user would like to see details of a specific product (for instance he wants to quickly find out orders containing "tomato" product). It would allow him to get data on specific product.

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Adding a filter "product" in Orders & Fulfillment reports.

**Comment by lin-d-hop** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/issues/11130
