### ISSUE TITLE
No Zoom Buttons on Maps in Embedded Groups

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/wishlist#42]
## Description

Users are finding it difficult to interact with the embedded groups map. Users and UK team have reported that the map should have +/- icons to zoom in and out of the map and not as current functionality dictates where  (cntrl+wheel have to be used)

## Expected Behavior

icons in the right bottom to zoom in and out with

## Actual Behavior

no icons to zoom therefore making the user experience difficult. The mouse and keyboard have to be used

## Steps to Reproduce

1. Go to an embedded map - https://www.biodynamic.org.uk/where-to-buy/
2. See lack of icons in bottom right
3. Use mouse and keyboard to scroll - unfriendly process
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/28807449/45517961-cce85600-b7a7-11e8-8896-da96c1ceb831.png)

## Context

Users have a bad experience when using the map

## Your Environment

* Version used: 
* Browser name and version: Chrome 68
* Operating System and version (desktop or mobile): Desktop 

## Possible Fix

Add the zoom icons

**Comment by YasuhiroYoshida** [comment]
I tried to reproduce this issue. Here is my results. I didn't get the details of the map. But I got the frame of the map, pins, and the zoom buttons in question. So it seems this issue has been solved, at least partially as it is not really located at the upper bottom corner; it came out on the upper right corner. I think this issue needs to be reviewed again. Or if I'm missing something, please let me know.

<img width="1226" alt="Screen Shot 2021-09-16 at 13 04 38" src="https://user-images.githubusercontent.com/892791/133593539-efc48b1f-5df1-4cad-a49c-9a1d8370d0c1.png">

**Comment by RachL** [comment]
Thanks for the feedback @YasuhiroYoshida . I could be wrong but I'm not sure this map comes from Open Food Network.

@lin-d-hop do you know more?

**Comment by RachL** [comment]
closing this one as we don't support embedded groups anymore
