### ISSUE TITLE
Enhance product description edition features

### ISSUE THREAD

**Issue by olivier5741** [openfoodfoundation/wishlist#427]
## What is the need / problem?

Product description edition features

## Which type of users does this problem affect (and how many, if known)?

* **Shoppers** : enhanced product information that's easy to process
* **Hub Managers (MCFEs), Producers, Instance Managers** : present all the product information (to respect national laws, EU laws at least) in nice way so hte shopper isn't overwhelmed by it and the shopper quickly identifies what matters to her/him.

## Potential solutions that will solve the problem  ?

* **Use markdown** 
* **Support additional html tags**
  * `<hr>`, breaks
  * `<br>`, single line carriage return (at the moment every line is new paragraph
  * tables tags, to show nutrient list
tables would be a nice addition (for nutrients)

## Connected wishlist and discovery discussions* [list precedent discussions]

From comment in issue
https://github.com/openfoodfoundation/openfoodnetwork/pull/10332#issuecomment-1461686644

> In short, enable something I just used to format this feature 😄 

Cheers,
Olivier

**Comment by lin-d-hop** [comment]
Using Trix editor which has already been done. Also might include removing an old angular WYSIWYG which is an added bonus.

No table functionality with Trix, but <hr> and <br>. PLus bullet points, strikethrough, headings etc etc. And undo/redo.

Happy to include in papercuts :tada:

**Comment by lin-d-hop** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/issues/11129
