### ISSUE TITLE
Provide a unit for width, height and depth

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#429]
## What is the need / problem?
The properties width, height and depth of a product variant don't have a unit displayed. So it's impossible for the user to know what to type, e.g. 0.1 (m) or 10 (cm) for a width of 10 cm.
For weight we have the unit displayed (kg).

![image](https://user-images.githubusercontent.com/1790176/226138009-08194b76-2297-4c02-a132-256072fa1364.png)

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers
- Instance Managers

## Potential solutions that will solve the problem
Provide the unit (I propose cm) in the same way we do it for weight (kg).

**Comment by lin-d-hop** [comment]
Suggestion to try this as a translation. If the translation key is used in other places as well then that would be a bug :)
