### ISSUE TITLE
Improve invalid number format treatment and UX on product bulk edit page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/wishlist#43]
**Problem description:**
On product edit page, if I fill in a number that has not a number format (ex: 2,50,50 or 2.50,2 or 2.50. or...) and try saving, the amount is replaced by "0" and I get no error message. So if I don't pay attention, I don't realize that the amount I tried to enter was not saved properly and replaced by 0.

![testing notes](https://user-images.githubusercontent.com/8135376/33020250-d8e3df4a-cdfd-11e7-85e9-87733b584cbd.jpg)

**Acceptance criteria:**
When I fill in a number that has not a number format and try saving:
- the system prevent saving
- the wrong amount I filled in is still there and appears in red 
- I see an error message "xxx. has an invalid format. Please enter a number."

**Comment by RachL** [comment]
woaaaa big mistake this is in test ready through a connexted pR, luckily github kept a copy. Closing
