### ISSUE TITLE
[Admin] Use same sorting for last name and first name on orders page and BOM page

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#437]
## What is the need / problem?
On the BOM page (/admin/orders/bulk_management) since [#10606](https://github.com/openfoodfoundation/openfoodnetwork/pull/10606) names are 
- displayed as Last name, First name (e.g. Einstein, Albert) and 
- sorted by Last name and then by First name when clicking on the column header 'name'.

It was agreed that we should have the same behavior on the orders page (/admin/orders) as well. The same method should be used.

New sorting on BOM page:
![image](https://user-images.githubusercontent.com/1790176/231487767-cc49ee9e-9943-4170-8e64-c1cbbfe442aa.png)

Current sorting on orders page:
![image](https://user-images.githubusercontent.com/1790176/231579888-dd756b4e-e6ac-4a0a-9ade-2dd0c4762d15.png)

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers
- Instance Managers

## Potential solutions that will solve the problem
Use the same method as on the BOM page.

## Connected wishlist and discovery discussions
[#10116 comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/10116#issuecomment-1430121891) and comments below.

**Comment by lin-d-hop** [comment]
80% sure this is a papercut..... so let's wrap in a timebox ;)
