### ISSUE TITLE
Select multiple orders using existing checkboxes, and perform key actions from Actions dropdown

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/wishlist#44]
## What is the problem we are solving 
The Order Management page now checkboxes where multiple orders can be selected. However the only function that can then be activated is the 'bulk invoice printing'

This is counter-intuitive and out of step with user expectations - key functions like cancelling orders, resending order confirmations etc could be activated from here.

There is already a box with a range of actions that can be taken on an order, accessible once you have opened a single order for editing

Can we just make this same box available on the order management page (replacing the Print Invoices single button), and enable it to be used on multiple orders that have been selected with checkboxes?

NB. It should include the existing Bulk Invoice Printing, as well as some or all of the options in image below

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/99550587-20de-4ffc-95ba-e93b6388850e)

There's a nicely styled 'Actions' box on the [Inventory page](https://openfoodnetwork.org.au/admin/inventory)
![image](https://user-images.githubusercontent.com/2911176/78468240-53cd9c80-7759-11ea-81d8-11e5d9c16334.png)

## Success factors = expected outcome 
I can select multiple orders using checkboxes, and perform key order actions (as per existing Actions dropdown with the order edit) on all of them with one click

**Comment by mulyaj** [comment]
Hey there, I've designed a potential mockup for this [located in this Figma file](https://www.figma.com/proto/PBNUA4ygpTiI1PUg51K9Yl/44-Select-Multiple-Orders?page-id=2%3A3&node-id=2%3A28&viewport=326%2C48%2C0.33&scaling=min-zoom&starting-point-node-id=2%3A28).

On top of the existing Actions dropdown on the Inventory, I've added an additional attached label box identifying how many selections a user has made. 

![Selections=True](https://user-images.githubusercontent.com/63881221/133004497-c92157d9-f2da-4976-91b5-04756b101545.png)

In addition, in the prototype, after a user has selected a key action, a dialog appears to confirm the action, notifying how many orders they've selected.

![OFN Confirmation Dialog](https://user-images.githubusercontent.com/63881221/133004721-5cb54ff8-bb21-451e-b185-e9628a57a6b7.png)

**Comment by RachL** [comment]
Papercut 1 : implementing the design with Bulk invoice printing, then we see for the other actions

**Comment by RachL** [comment]
First issue : https://github.com/openfoodfoundation/openfoodnetwork/issues/9316

**Comment by RachL** [comment]
Cancelling: https://github.com/openfoodfoundation/openfoodnetwork/issues/9422

Closing this issue here. Let's see if there is a need to ship in bulk. 

We spoke about capturing in bulk during papercut meeting, but this was for sure outside of papercut territory.
