### ISSUE TITLE
Show pop-up alert when clicking 'ship' button from Orders screen

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/wishlist#451]
## What is the need / problem?
In the UK we see fairly regular occurrences of confused customers who have been sent 'order shipped/pick-up notification' emails for old orders. This happens because the enterprises are trying to 'tidy up' their orders list; an order which has been paid for, and not marked as shipped, appears as 'READY' in the shipment column. An order marked as shipped will appear as 'SHIPPED'. Enterprises don't often realise that clicking this button sends a confirmation of shipment/pick-up email to the customer. This is mentioned in the [user guide](https://guide.openfoodnetwork.org/basic-features/orders/view-orders#:~:text=see%20below).-,When,-a%20shop%20or), but many aren't seeing this.

## Which type of users does this problem affect (and how many, if known)?
_e.g._
- Shoppers
- Hub Managers (MCFEs)
- Producers

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Adding a pop-up alert when this button is clicked stating that clicking it will send an email to the customer e.g. mock-up below:
<img width="389" alt="Screenshot 2023-07-11 at 13 55 39" src="https://github.com/openfoodfoundation/wishlist/assets/100226210/4b2e7667-c0d8-465b-8590-ff3b59944f7a">

In an ideal world, this alert could only display when the order was created over a month ago. This would prevent the pop-up from adding an extra click for enterprises who use the ship button 'correctly' (i.e. to inform customers their order has shipped/been collected), whilst ensuring that enterprises using this button to tidy up their order lists will be warned about the email trigger.

**Comment by RachL** [comment]
Papercut confirmed, let's not forget the second ship button:

![image](https://github.com/openfoodfoundation/wishlist/assets/6525576/f861ef53-27b9-4c5d-b25e-a5f4ada57bd9)

**Comment by RachL** [comment]
Opened https://github.com/openfoodfoundation/openfoodnetwork/issues/11602
