### ISSUE TITLE
Show pop-up alert when navigating away from /summary page without placing order

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/wishlist#453]
## What is the need / problem?
Hubs are reporting that users believe they've placed an order, but have instead navigated away from the checkout/summary page without clicking 'complete order'. Below is a quote from a hub but we've had multiple other reports of this.

`We've had 3 people in the last few months thought they'd ordered but they hadn't pressed the final compete order button so hadn't received their order confirmation email, but they thought they had checked out. I nearly did it myself once. I think you have to press 3 buttons on the three different pages before you're checked out fully. Has this been raised by anyone else, is there anything that can be done like a pop up that says are you sure you want to leave this page? Or a reminder saying you have things in your basket?`

## Which type of users does this problem affect (and how many, if known)?
- Shoppers

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
- Add a pop-up soft warning when users attempt to navigate away from this page without clicking the complete order button (i.e. click browser back button/close browser/navigate away from page) e.g. 'Are you sure you want to leave this page? Your order has not been placed'
<img width="389" alt="Screenshot 2023-07-11 at 13 55 39" src="https://github.com/openfoodfoundation/wishlist/assets/100226210/d49f0a8e-e3a5-480c-a671-1d72e20caf3e">

- Change the colour of the 'complete order' button to OFN orange, in line with preceding checkout pages. Green implies 'done', i.e. the order has successfully been placed, which at this point it hasn't. 
Proposed:
<img width="500" alt="Screenshot 2023-07-17 at 10 36 20" src="https://github.com/openfoodfoundation/wishlist/assets/100226210/d882afee-8b54-4062-a689-12a959136e97">

Original:
<img width="500" alt="Screenshot 2023-07-17 at 10 40 43" src="https://github.com/openfoodfoundation/wishlist/assets/100226210/e9e9f698-73fa-42ce-ab33-0e160ecb20ad">

**Comment by RachL** [comment]
Modal warning when closing / reloading / clicking on a button that changes the URl: yes it's a papercut.

exception: if the user goes back in the checkout process (step2 or 1 or goes back to the cart or uses the browser back button) then we should not introduce the modal: this part can be tricky.

**Comment by RachL** [comment]
Opened https://github.com/openfoodfoundation/openfoodnetwork/issues/11600 for this
