### ISSUE TITLE
[Reports] Display results even if date range end is set before date range start

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#460]
## What is the need / problem?
If the user thinks of the date range in the wrong direction (start is now and end is in the past), then no results will be shown. This can be confusing.

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers
- Instance Managers

## Potential solutions that will solve the problem
If end date is set before start date, the just swap them in the query.

**Comment by drummer83** [comment]
Hmm, is there a definition of 'start' and 'end' that implies end > start? I think it's valid to think that start is 'now' and the selected time span extends into the past - so end will be in the past. 
In general I prefer having some sort of smart software that assumes what you probably meant and just fixes it for you - but that's a personal preference.

**Comment by lin-d-hop** [comment]
In the case that someone enters a typo a swap would be even more confusing.

Agree with @RachL that an error message would be better.
If we had error message patterns we could just say 'implement with x error message'
But until that time we need to say 'Needs Design' and 'Confirmed Papercut'

**Comment by RachL** [comment]
@drummer83 now that we have a date range tool I think we can close this one. Please reopen if I got this wrong.
