### ISSUE TITLE
Hide all references option should hide a supplier from details section of a shop

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/wishlist#465]
## What is the need / problem?

`Hiding all references` option is hiding _almost_ all references... except if the hub/producer is supplying a distributor. In that case, it still appears as such:

![image](https://github.com/openfoodfoundation/wishlist/assets/49817236/58d00127-4078-4996-b4e3-8072ae24fe5c)

## Which type of users does this problem affect (and how many, if known)?

_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]

Remove the listing, if a supplier as selected the option `Hide all references`

## Connected wishlist and discovery discussions* [list precedent discussions]

https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1692790903146679

## Additional context

Note to testers/devs: shopfront page needs to be hard-refreshed (`ctrl + F5`) for the enterprise settings to take place.

**Comment by lin-d-hop** [comment]
Probably not a papercut cos its a bit curly.
Has a user ever reported this?

**Comment by lin-d-hop** [comment]
More of a bug than a feature request.

And @filipefurtad0 confirms this has been reported by a user.

**Comment by filipefurtad0** [comment]
Ok, let's close this it then :ok_hand:  We can re-open should it become a requirement in the future.
