### ISSUE TITLE
Add Tag field to simple, producer-only order cycle interface

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/wishlist#47]
## Description
We have the ability to setup tag rules showing/hiding OCs. However this can't be done for a producer only OC, because there is no field to type the tag. In a hub OC you see the tag field in the outgoing section, but this isn't there for simple OCs.

## Expected behavior
![screenshot from 2018-06-12 17-05-35](https://user-images.githubusercontent.com/8135376/41299054-e0731c98-6e62-11e8-8f61-c8f5a039b3f3.png)

## Steps to Reproduce
1. Look at any producer only OC, you'll notice there's no tag field

## Animated Gif/Screenshot
This shows the simple OC view...
![image](https://user-images.githubusercontent.com/10843056/37382928-b4fcc894-2799-11e8-9cb2-13b251816a67.png)

This is where tags are applied to OCs in complex OCs...
![image](https://user-images.githubusercontent.com/10843056/37383024-2be4c326-279a-11e8-9ba0-6f757b17ffa4.png)

See above the mockup for the expected behavior (see if that makes sense)

## Context
I haven't had a user request this yet, but it's part of our core functionality, and it should be a simple fix.

## Severity
3 - not too many users are impacted, but it is core functionality

## Possible Fix
Add tag field to simple OCs

**Comment by RachL** [comment]
Created https://github.com/openfoodfoundation/openfoodnetwork/issues/9248 to avoid re-migrating long history of comments.

Closing here.
