### ISSUE TITLE
Missing shipping method description and "ready for" information on both PDF-invoice templates

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/wishlist#48]
## Description

Shipping instructions appear on email-generated order confirmations, but are absent from the PDF version of the respective invoices.

## Expected Behavior

Updated according to discussion (see below):
All PDF-invoices (both templates) should contain shipping and order-cycle information.

## Actual Behaviour

Only email-embedded order confirmations have this information.

## Steps to Reproduce

1. Admin: Create a shipping method with shipping instructions. Open an order cycle with at least one item with available stock.
2. Customer: Place an order on that order cycle.
3. Admin: Generate PDF-invoices by:
 a) - Bulk printing an invoice (pdf), on the Orders page (/admin/orders?q[s]=completed_at+desc)
 On order edit page, (/admin/orders/Rxxxxxxx/edit)
 b) Print invoice (pdf)
 c) Send the invoice (pdf per email)
 d) Resend (email, no pdf)
4. Verify that a) b) c) do not show shipping instruction -> the bug.
5) Verify d) does.

## Animated Gif/Screenshot

- Order confirmation per email:

![image](https://user-images.githubusercontent.com/49817236/87885624-3920ea00-ca0f-11ea-8eef-350d0c2b09ff.png)

- PDF-invoice:

![image](https://user-images.githubusercontent.com/49817236/87885709-65d50180-ca0f-11ea-9a50-c1d7be2d518a.png)

## Workaround

Consider the info displayed on checkout and/or see info received per Email. 

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.1.0
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop/Ubuntu

## Possible Fix

Observed while testing PR openfoodfoundation/openfoodnetwork#5712

**Comment by audez** [comment]
Big up 😁 
We have a shop manager that has asked for the "ready for" info be added in the invoices. He also would like this information to be displayed in the Orders list and orders details, so I'm going to open another issue for this.

**Comment by audez** [comment]
Today we have 2 more producers that asked for the "shipping method" to be displayed on the invoices.

**Comment by RachL** [comment]
will be fixed with new template
