### ISSUE TITLE
Enable product search on the whole product name

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/wishlist#498]
_Transferred from Discourse_

## What is the need / problem?

Mary and Shannon need to create themselves orders for some users, for instance for a late order after the order cycle was closed, or for old people who don’t manage to order themselves. Or for on-site “on the shelf” sales.

Today when they create an order and want to add a product, they cannot preview the products available, and they have to type exactly the FIRST three letters of the product name, else the product doesn’t show and can’t be added to the order. So if Mary doesn’t remember very well how she (or the producer) named the products, she has troubles to fill in the order.

## Which type of users does this problem affect (and how many, if known)?

Hub managers

## What is the current impact of this problem

**Time consuming for the hub manager, and annoying:** the hub manager needs to open a new tab with the product list to see how they named the products which is very unpractical.

## What is the benefit in focusing on this

- It will make it much easier for a hub manager to fill in an order for a customer.
- It will make it much easier for a hub manager to capture an order on site (for sales “on the shelf”)

## Potential solutions that will solve the problem?

Apply on the back office the same “search rule” as in shopfront (see GH issue) = when I type 3 letters, when the product name CONTAINS those three letters, the product is displayed

## Connected wishlist and discovery discussions

https://community.openfoodnetwork.org/t/enable-product-search-on-the-whole-product-name/1144/1

Github issue with a first level of speccing: https://github.com/openfoodfoundation/openfoodnetwork/issues/1990

**Comment by drummer83** [comment]
I think we have already implemented this:

https://github.com/openfoodfoundation/wishlist/assets/1790176/a3a3724f-86d0-4240-9aed-d1dfb36a0465

**Comment by sigmundpetersen** [comment]
Thanks for testing @drummer83 👍
Closing
