### ISSUE TITLE
[Reports] Add a "payout report"

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/wishlist#506]
## What is the need/problem?

Hub need to be able to see quickly how much they owe each producer. And / or to use data in an integration to send producers purchase orders for example

Reports columns : 

- Name of the producer
- Producer’s address
- Producer’s ABN/ACN
- Producer’s email
- Name of Hub
- Hub’s address
- Hub’s postal code
- Hub’s contact email
- Order number
- Order date
- Name of order cycle
- Order cycle start date
- Order cycle end date
- Name of product
- Variant unit name
- Quantity ordered
- total product without fees and tax
- total product with producers fees and without tax
- total producers fees without tax
- total producer fees tax
- total tax (incl. producer fees)
- Total amount incl. tax and producers fees (and excl. hub fees)

Report filters :

- date range
- hub
- producer
- order cycle

+usual rendering options

## What type of users does this affect (and how many, if known)?

- Hub Managers (MCFEs)
- Producers

## Additional context

example of an output the file can make easier: https://drive.google.com/file/d/1GLi9sndnL9zo98Eo17uyyEe-SfHPHht6/view

**Comment by dacook** [comment]
This report appears pretty straightforward. 
Would there be any filter options? I guess filter by hub (if user has access to more than one hub) and by producer.


I guess that any purchase order integration/email would be triggered by order cycle closing.

We can [add a webhook](https://github.com/openfoodfoundation/openfoodnetwork/issues/10528) for that event pretty easily, but it wouldn't contain the information needed to send purchase orders. However it could be used by a middleware like n8n to then access the necessary information (by this report, or orders api) and build the emails.

**Comment by rioug** [comment]
@RachL 

It looks like the report Order Cycle Distributor Totals by Supplier could be good base for this : 
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/reporting/reports/orders_and_fulfillment/order_cycle_distributor_totals_by_supplier.rb
And it looks the xero invoice report might be helpful as well : https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/reporting/reports/xero_invoices/base.rb

Rough estimate : 
* setting the report, and various filter:  **0.5 days**
* handling total calculation: **1.5 days**
* extra 20% to cover unforeseen problem : **0.4** 
**Total:   2.4 days**

It's a bit hard to tell how difficult it's going to be to calculate the various total. I believe the data is there so it's just a matter of combining the various adjustments. 
Correct me if I am wrong, but as fas as I understand we don't need to worry about voucher for this report. A voucher covers the part of the payment to the hub, but it doesn't affect how much the hub owes to a producer.

**Comment by RachL** [comment]
To keep some history, I will transfer this issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/12776 to the main repo when ready
